<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>car_bmw_528i</name>
   <tag></tag>
   <elementGuidId>1a18acee-8caf-4673-8d58-1781f8da636e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/main/div/section/div/div[1]/div/div[3]/div/div[2]/div/ul/li[6]/span/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.fusion-layout-column.fusion_builder_column.fusion-builder-column-9.fusion-flex-column.postcard-product.fusion-column-inner-bg-wrapper.post-card.fusion-grid-column.fusion-post-cards-grid-column.product-grid-view.product.type-product > span.fusion-column-inner-bg.hover-type-none > a.fusion-column-anchor > span.fusion-column-inner-bg-image.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='content']/div/div/div/div[3]/div/div[2]/div/ul/li[7]/span/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bc89e48e-3d42-4ab2-9722-9fdf178e4df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fusion-column-inner-bg-image lazyloaded</value>
      <webElementGuid>0c9ee4a1-a05a-4c0d-9c62-634fb26ce06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bg</name>
      <type>Main</type>
      <value>https://getgo.sg/wp-content/uploads/2022/12/BMW-X3-3rdgen.png</value>
      <webElementGuid>1a7731e1-6121-4077-891e-307a1b9286a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/main/div/section/div/div[1]/div/div[3]/div/div[2]/div/ul/li[6]/span/a/span</value>
      <webElementGuid>1a93dbd3-dbb7-4b81-a6d5-208df8a13fe4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/div/div/div[3]/div/div[2]/div/ul/li[7]/span/a/span</value>
      <webElementGuid>b30b83a5-f1cc-4d86-b723-f025190a8f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/span/a/span</value>
      <webElementGuid>c4afa71a-d02b-4730-835f-747cf2603742</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
