<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bmw_528I</name>
   <tag></tag>
   <elementGuidId>0af4aa37-c8f7-45f0-b35a-54c537456f46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'https://getgo.sg/wp-content/uploads/2022/12/BMW-X3-3rdgen.png']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-responsive.wp-image-11035.lazyautosizes.ls-is-cached.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='post-11039']/div/div/div/div[2]/div/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>65f50c6f-90ff-4aa2-9805-2a2b97bbcc5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>018b60b2-41ba-4127-88a4-fbcc9af8d39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>05e7ad43-3288-4a9c-87d9-b6bb8930c2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>c88b777e-d00b-40b6-b6ab-9b28abc83f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>427</value>
      <webElementGuid>59a7ed30-fea0-4185-b67e-4e1c1bb8c477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://getgo.sg/wp-content/uploads/2022/12/BMW-X3-3rdgen.png</value>
      <webElementGuid>2cb3a3f4-7695-46b7-8ca6-8bf5b9765e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orig-src</name>
      <type>Main</type>
      <value>https://getgo.sg/wp-content/uploads/2022/12/BMW-X3-3rdgen.png</value>
      <webElementGuid>bbda1d72-486f-41f5-85b9-4b55c83bc780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive wp-image-11035 lazyautosizes ls-is-cached lazyloaded</value>
      <webElementGuid>89565c3b-3bbe-4faf-b5c2-eb12f0c13385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://getgo.sg/wp-content/uploads/2022/12/BMW-X3-3rdgen-200x107.png 200w, https://getgo.sg/wp-content/uploads/2022/12/BMW-X3-3rdgen-400x214.png 400w, https://getgo.sg/wp-content/uploads/2022/12/BMW-X3-3rdgen-600x320.png 600w, https://getgo.sg/wp-content/uploads/2022/12/BMW-X3-3rdgen.png 800w</value>
      <webElementGuid>d2753639-4dfe-4e47-8cd6-46beb56b60bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://getgo.sg/wp-content/uploads/2022/12/BMW-X3-3rdgen-200x107.png 200w, https://getgo.sg/wp-content/uploads/2022/12/BMW-X3-3rdgen-400x214.png 400w, https://getgo.sg/wp-content/uploads/2022/12/BMW-X3-3rdgen-600x320.png 600w, https://getgo.sg/wp-content/uploads/2022/12/BMW-X3-3rdgen.png 800w</value>
      <webElementGuid>598775be-fdd8-4696-854c-7f6b6835dc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sizes</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>d0b24c46-0d67-49d9-92e4-bd767409c661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orig-sizes</name>
      <type>Main</type>
      <value>(max-width: 800px) 100vw, 800px</value>
      <webElementGuid>c7e5054c-8435-4b77-b337-7c8641b4df13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>744px</value>
      <webElementGuid>b672ae65-d190-4f9b-b914-45724a935006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-11039&quot;)/div[@class=&quot;post-content&quot;]/div[@class=&quot;fusion-fullwidth fullwidth-box fusion-builder-row-1 fusion-flex-container nonhundred-percent-fullwidth non-hundred-percent-height-scrolling&quot;]/div[@class=&quot;fusion-builder-row fusion-row fusion-flex-align-items-flex-start fusion-flex-content-wrap&quot;]/div[@class=&quot;fusion-layout-column fusion_builder_column fusion-builder-column-1 fusion_builder_column_3_5 3_5 fusion-flex-column&quot;]/div[@class=&quot;fusion-column-wrapper fusion-column-has-shadow fusion-flex-justify-content-flex-start fusion-content-layout-column&quot;]/div[@class=&quot;fusion-image-element&quot;]/span[@class=&quot;fusion-imageframe imageframe-none imageframe-1 hover-type-none&quot;]/img[@class=&quot;img-responsive wp-image-11035 lazyautosizes ls-is-cached lazyloaded&quot;]</value>
      <webElementGuid>6ef46c87-044c-432e-b845-4f826bb19a21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-11039']/div/div/div/div[2]/div/div/span/img</value>
      <webElementGuid>e10e1817-532b-49b1-ad59-dfea09712c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://getgo.sg/wp-content/uploads/2022/12/BMW-X3-3rdgen.png')]</value>
      <webElementGuid>a18337b0-c357-4424-aed2-2677fb3fdd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>66d2f71c-4dea-4241-a977-57fb2dcf01b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://getgo.sg/wp-content/uploads/2022/12/BMW-X3-3rdgen.png']</value>
      <webElementGuid>69fea2e9-9018-4991-917d-e02bc056c399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
