<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_bmw_528i</name>
   <tag></tag>
   <elementGuidId>790551fb-e1ee-4b9b-81a0-cbfec206db1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/main/div/section/div/div/div[1]/div/div[1]/div/div[2]/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.fusion-title-heading.title-heading-left.fusion-responsive-typography-calculated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='post-11039']/div/div/div/div/div/div[2]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>09f6414b-10a6-4178-90c9-d9714751ace4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fusion-title-heading title-heading-left fusion-responsive-typography-calculated</value>
      <webElementGuid>27286fc4-0861-4657-a1a9-add7fac20104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BMW X3 2.0 3rd Gen</value>
      <webElementGuid>c12593d8-0379-418b-8f1d-547a4e12b00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/main/div/section/div/div/div[1]/div/div[1]/div/div[2]/h1</value>
      <webElementGuid>b52a3821-7f27-432e-adb1-6029f47ce27a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-11039']/div/div/div/div/div/div[2]/h1</value>
      <webElementGuid>b7989292-2db1-49c5-8df4-3a9b6bb08a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[3]/following::h1[1]</value>
      <webElementGuid>645be02c-0144-4de4-8a67-253db9b6e22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[3]/following::h1[1]</value>
      <webElementGuid>9e2e69f9-e1f1-41c7-9068-41396454afd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book now'])[1]/preceding::h1[1]</value>
      <webElementGuid>1fdc7058-4c4f-42e3-830d-93e476e8a74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About the car'])[1]/preceding::h1[1]</value>
      <webElementGuid>9080b669-bf5b-40b4-9c69-9449a66104f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BMW X3 2.0 3rd Gen']/parent::*</value>
      <webElementGuid>cfb97c60-d4e2-45db-b33a-3eda6c671683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>ec2f324c-a1c8-408c-932a-ce72afbb1780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'BMW X3 2.0 3rd Gen' or . = 'BMW X3 2.0 3rd Gen')]</value>
      <webElementGuid>0bbb9adf-9494-400e-92ed-95d6738548bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
